name: Deploy PHP Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.9'

      # - name: Install Composer Dependencies
      #   run: composer install

     
      - name: Deploy Website to EC2 Instance
        run: |
          # Create a temporary file to store the SSH private key
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2-ssh-key.pem
          
          # Set permissions on the key file
          chmod 600 /tmp/ec2-ssh-key.pem

          # Copy PHP files to EC2 instance
          scp -i /tmp/ec2-ssh-key.pem -r ./ ec2-user@54.167.247.203:/path/to/destination

          # Connect to EC2 instance and execute further commands
          ssh -i /tmp/ec2-ssh-key.pem ec2-user@54.167.247.203"cd /path/to/destination && composer install"

          # Reload or restart your web server (e.g., Apache)
          ssh -i /tmp/ec2-ssh-key.pem ec2-user@54.167.247.203"sudo systemctl reload httpd"

      - name: Remove the temporary key file
        run: rm /tmp/ec2-ssh-key.pem

# ... (other parts of your workflow)