name: Deploy PHP Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.0'

      - name: Install Composer Dependencies
        run: composer install

      - name: Deploy Website to EC2 Instance
        run: |
          # Copy PHP files to EC2 instance
          scp -i ${{ secrets.EC2_SSH_KEY }} -r ./ user@your-ec2-ip:/path/to/destination

          # Connect to EC2 instance and execute further commands
          ssh -i ${{ secrets.EC2_SSH_KEY }} user@your-ec2-ip "cd /path/to/destination && composer install"

          # Reload or restart your web server (e.g., Apache)
          ssh -i ${{ secrets.EC2_SSH_KEY }} user@your-ec2-ip "sudo service apache2 reload"
